apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-cluster
  region: us-west-2
  version: "1.16"
vpc:
  id: vpc-0c4f3a4bc48f8a4ea
  securityGroup: "sg-0fc0db305fa6a3e98"
  subnets:
    public:
      us-west-2a: { id: subnet-0e33771e10e26554c }
      us-west-2b: { id: subnet-09b54fd81c7caf180 }
      us-west-2c: { id: subnet-01f7d3d23892be5c1 }
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  serviceRoleARN: "arn:aws:iam::479516992638:role/EksClusterRole"
managedNodeGroups:
  - name: dev-nodes
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    instanceType: t3.medium
    iam:
      instanceRoleARN: arn:aws:iam::479516992638:role/EksNodeRole
